name: Configuración de Base de Datos

on:
  push:
    branches:
      - main  # Este workflow se ejecuta en el push a la rama main

jobs:
  setup-database:
    runs-on: ubuntu-latest  # Usamos un runner con Ubuntu

    services:
      mysql:
        image: mysql:8.0  # Usamos la imagen oficial de MySQL
        env:
          MYSQL_ROOT_PASSWORD: root_password  # Contraseña del usuario root de MySQL
        ports:
          - 3306:3306  # Exponemos el puerto 3306

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3  # Este paso sirve para obtener el código del repositorio

      - name: Configurar variables de entorno con secretos
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}  # Cargar el nombre de usuario desde los secretos
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Cargar la contraseña desde los secretos
          DB_HOST: ${{ secrets.DB_HOST }}  # Cargar el host desde los secretos
          DB_PORT: 3306  # Puedes definir el puerto aquí si siempre es el mismo
          DB_NAME: ${{ secrets.DB_NAME }}  # Cargar la base de datos desde los secretos

      - name: Crear usuario en MySQL
        run: |
          echo "Creando usuario de base de datos..."
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h ${DB_HOST} -P ${DB_PORT} -e "CREATE USER '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';"
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h ${DB_HOST} -P ${DB_PORT} -e "GRANT ALL PRIVILEGES ON *.* TO '${DB_USERNAME}'@'%';"
          mysql -u root -p$MYSQL_ROOT_PASSWORD -h ${DB_HOST} -P ${DB_PORT} -e "FLUSH PRIVILEGES;"

      - name: Verificar conexión con el usuario
        run: |
          echo "Probando conexión con el usuario ${DB_USERNAME}..."
          mysql -u ${DB_USERNAME} -p${DB_PASSWORD} -h ${DB_HOST} -P ${DB_PORT} -e "SHOW DATABASES;"
