name: Configuraci贸n de Base de Datos

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Configurar variables de entorno con secretos
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Crear usuario en MySQL
        run: |
          echo "Creando usuario de base de datos..."
          mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -h localhost -P 3306 -e "CREATE USER '${{ secrets.DB_USERNAME }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
          mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -h localhost -P 3306 -e "GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.DB_USERNAME }}'@'%';"
          mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -h localhost -P 3306 -e "FLUSH PRIVILEGES;"

      - name: Verificar conexi贸n con el usuario
        run: |
          echo "Probando conexi贸n con el usuario..."
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -h localhost -P 3306 -e "SHOW DATABASES;"
